name: Clean Image Tags
description: |-
  Delete old image tags


inputs:
  token:
    description: Token for Github API
    required: true
  leave:
    description: The amount of tags to leave
    default: "2"
    required: false
  package_name:
    description: Package name
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |-
        ids_to_delete=($(curl -sL -X 'GET' \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/users/alexdenisova/packages/container/${{ inputs.package_name }}/versions" \
          | jq -r "sort_by(.updated_at) | reverse | .[${{ inputs.leave }}:] | .[] | .id"))

        for id in "${ids_to_delete[@]}"; do
          curl -sL -X 'DELETE' \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/users/alexdenisova/packages/container/${{ inputs.package_name }}/versions/${id}"
          echo "Deleted image with id $id"
        done
